### PR TITLE
Android SDK and build.gradle update.

### PR DESCRIPTION
**Pull request by YadhuYk007**
Android release build was failing with 'AAPT: error: resource not found' . Updating SDK along with dependency syntax in build.gradle

### CODE REVIEW

**Comment by shivlahejat** [comment]
ff

**Comment by nitish24p** [comment]
Hey can you also make a change in package.json and do a minor version update

**Comment by YadhuYk007** [comment]
@nitish24p What changes are you planning in package.json? 
I had already updated android sdk version in the PR.

**Comment by nitish24p** [comment]
@YadhuYk007 I need to publish a new version to npm right.. can you make a minor increment of the version in package json

**Comment by YadhuYk007** [comment]
Hi, I have updated the version. Please check the same.

**Pull request merged**
